### ISSUE TITLE
How to explore interaction by a covariate in trajectory analysis 

### ISSUE THREAD

**Issue by fliang1976** [CecileProust-Lima/lcmm#100]
Dear Sir or Madam,
I have two questions when I did trajectory analysis using hlme function.
1) I added covariates (i.e. age and gender) in modeling the trajectory via hlme function. After I obtained the optimal number of latent classes, I want to examine the adjusted association between the trajectory and mortality using Cox regression analysis. Should I control for the same covariates (i.e. age and gender) in the COX regression model? I am a bit confused. I believe that the trajectory I obtained is independent of age and gender, and thus it is not necessary to control for these covariates in the cox regression model. I am not sure if it is correct or not.
2) I also want to explore if the trajectories vary by gender. That is, I want to explore the interaction between gender and time in the trajectory analysis model . Should I get the best latent class model first and then examine interaction in the best model or just examine the interaction in one latent class model?

Thank you !

Best Regards,
Feng Liang

**Comment by CecileProust-Lima** [comment]
Dear Feng, 
regarding your questions: 
1. Every combination can make sense according to the type of data and objective. The adjustment in the Cox model could make sense too. By the way, there is a joint model for the joint analysis of longitudinal data and survival data in jointlcmm function. 
2. it depends. If you want to explore the heterogeneity in each group separately, you could stratify your analyses. Otherwise, you could also adjust on gender and seek residual heterogeneity as in 1. 
Cécile
