### ISSUE TITLE
Model validation and missing data

### ISSUE THREAD

**Issue by martinschlund** [CecileProust-Lima/lcmm#104]
Hi Cecile, 

First of all thank for your great work with this package, it is much appreciated!
I have two issues, which I have not been able to find clear answers to from going over the responses in the closed issues. I should say that I am new to this package and appologize in advance if I am asking the obvious. 

I am using lcmm() to model the trajectory of a biomarker over the first 3 days in ~470 patients in the intensive care unit and obtain latent classes for the biomarker trajectory which I will then correlate with clinical outcomes. I am only modelling the trajectory on time and without any covariates. 
 
1) Missing data. As I understand it, lcmm treats missing data as MAR, meaning that missingness can be predicted from the observations. In my case, samples will be missing because patients were either discharged or died. This will have some but not perfect correlation with the observed values of the biomarker (patients with low initial values will have a higher chance of discharge and likewise patients with high initial values will have a higher risk of dying). Will this be suffiecient for the missing data mechanism in lcmm() to work in your opinion?

2) Model validation, When I have fitted the optimal model with latent classes I am interested in estimating the stability of the latent classes found and the class specific trajectories, ie would lcmm find latent classes with (approximately) the same trajectories if applied to a new dataset of ICU patients that are mostly but not completely similar to the original cohort. In lack of a validation cohort I would use a random sampling approach. 

First of all, I'm not sure if this is how it is done with latent class mixed modelling? I found some papers that did so in various ways but some did not do any model validation. What is your opinion on that?

Second, I am not sure how to best estimate the stability of the model. For machine learning algorithms I would perform k-fold cross-validation and get some average of model fit. But I am more interested in comparing the class-specific trajectories. Right now I am leaning towards splitting the dataset 50/50 randomly several times, applying the lcmm() (using gridsearch with the same settings each time), get predictions for each model with predictY and compare the predicted values. Would you find this prudent or do you suggest another way of verifiying model stability?

UPDATE: I have tried this below to automatize the model estimation process for many dataframes (to illustrate the idea of having multiple randomly split datasets and apply the model to each of them for comparison), however, I ran in to problems. Maybe you can figure out where it goes astray?

```
library(lcmm)
library(tidyverse)
library(NormPsy)

data("paquid")

paquid <- paquid %>% 
  mutate(age65 = (age-65)/10, 
         normMMSE = normMMSE(MMSE))

m1 <- hlme(normMMSE ~ age65+I(age65^2)+CEP,random =~ age65+I(age65^2), subject = 'ID', data = paquid)


df <- tibble(n = c(1:5), data = list(as.data.frame(rep(paquid, 5)))) #creates nested tibble with list of dataframes

model_function1 <- function(df){
  hlme(normMMSE ~ age65+I(age65^2)+CEP,random =~ age65+I(age65^2), subject = 'ID', data = df) #defines initial model function
}

df <- df %>% 
  mutate(m1 = map(data, model_function1)) #this works

model_function2 <- function(df){
  gridsearch(hlme(normMMSE ~ age65+I(age65^2)+CEP,  random =~ age65+I(age65^2), subject = 'ID', 
                  data= df , ng = 2, mixture=~age65+I(age65^2)), rep=100, maxiter=30, minit=m1) #defines modelling function with gridsearch
}

df <- df %>% 
  mutate(m2 = map(data, model_function2)) #this does not work 

```

Hope that my questions make sense. 

Looking forward to your response. 

Best regards

Martin S-L.

**Comment by CecileProust-Lima** [comment]
Hi, 
regarding your first point on missing data. Assessing whether MAR assumption holds is usually impossible but in my experience, the mixed model is usually quite robust. however, if you suspect a problem of MNAR, you can jointly estimate the risk of dropout with jointlcmm. 
The second question is complex to address. I have never tried to do this actually. At the individual level, this would be difficult since the latent class membership is not known. Maybe assessing the classification entropy on the new class could help see whether the classification remains discriminative. After that, if what you want to assess are the mean profiles, maybe a comparison of the predictions may be possible but not sure it is easy to find a metric that may help assess whether the predictions are really the same or not ... Maybe other users have a good experience in that. 
Regarding the last problem, I will let Viviane Philipps look at that. 
Cécile

**Comment by VivianePhilipps** [comment]
Hi,

the gridsearch function was unusable inside another function because it was systematically looking for the data in the global R environment. So it tried to apply the hlme function on the whole df tibble instead of applying it on each of its subdata. 
I updated the code to avoid such problems. The github's master branch should be fine for such situations.
Thank you for your feedback.

Viviane

**Comment by martinschlund** [comment]
Thank you both for your detailed responses and once again for a great package :-).
