### ISSUE TITLE
Truncated Data

### ISSUE THREAD

**Issue by kritchaiv** [CecileProust-Lima/lcmm#105]
Dear Dr Proust-Lima,

I hope you are well and many thanks for all your help with my previous enquiries.

I want to clarify something about missing data and how the package handles this. Currently, I am working on a data set of patients in ITU and trying to analyse the trajectories based on the patient's daily clinical or biochemical parameters. These parameters were measured daily for 28 days and would be stopped when they were discharged from ITU or passed away, resulting in truncated data.

From our previous correspondence, you explained that missing data would be treated as MAR and the assumption was that the dropout could be predicted from observations. However, the truncated nature of our data is not missing at random as it is informed by the preceding clinical condition. I also wonder to what extent the clustering algorithm is influenced by patterns within the truncated data (eg it will identify a cluster for patients just because they have fewer observations than others?). I wonder if you had encountered methods to account for these kind of data?

Thank you so much for your insight on this.

Best wishes,
Jay

**Comment by CecileProust-Lima** [comment]
Hi, 
what I meant is that, if the truncation (discharged from ITU / death) is entirely predictable by the preceding observations, then the MAR assumption holds. Otherwise, it would be worth jointly estimating the risk of dropout. 
Regarding the clusters, depending on the association between the trajectory of the marker and the risk of dropout, the clusters may or may not identify groups of subjects with a different follow-up time. In either case, this may be not a problem. 
Cécile
