### ISSUE TITLE
Missing data in lcmm

### ISSUE THREAD

**Issue by AlixCovenant** [CecileProust-Lima/lcmm#108]
Thank you for creating this forum. I know this is probably a basic question but could you please confirm how missing data is dealt with by lcmm. Specifically, I want to use lcmm to run GMM on a relatively large sample with some missing data and need to know if I need to impute the missing data first or if it is dealt with by lcmm either by FIML or some other method.  Thank you for your time. Alix

**Comment by CecileProust-Lima** [comment]
Hi, 
lcmm can include missing data on the dependent (Y) variables. The inference is based on the maximum likelihood so that estimates are robust to missing at random data. 
However, lcmm does not handle missing data on the covariates (X). Missing observations are removed from the analysis. The number of removed observations is indicated in the summary. 
Cécile

**Comment by AlixCovenant** [comment]
Thank you very much for clarifying this, I am very grateful for you taking the time to come back to me.
