### ISSUE TITLE
Class membership and latent variable prediction

### ISSUE THREAD

**Issue by tspmgh** [CecileProust-Lima/lcmm#114]
Dear Cecile,

I have fitted a hlme model and identified 4 trajectories/classes following the vignette - subsequently I am seeking to examine possible predictors for the class membership i.e. if the trajectories correspond to another variable not included in the model. Is there a prefered way/methodology to do this?

Would one fit a multinomial model with class as outcome and include the posterior probabilites for class membership and "the variable examined" as predictors? Sorry if this seems trivial.

Thanks in advance, bw.

**Comment by VivianePhilipps** [comment]
Hello,

linking the latent classes to external data is not obvious at all. We would recommend to fit again a hlme model including the external predictors. In your case, the predictors would be included in the class membership model (argument classmb of the hlme function), and you would fix all parameters related to the longitudinal trajectories in order to preserve the identified classes.
In that way, the uncertainty in the estimated latent structure will be taken into account, which would not be the case if you fit a multinomial model with class as outcome.

Best,

Viviane

**Comment by CecileProust-Lima** [comment]
Let me add that you will find a section on this (with references) in our new paper on a latent class model for multivariate longitudinal markers and times-to-event estimated with mpjlcmm function: [https://arxiv.org/abs/2202.05124](https://arxiv.org/abs/2202.05124)
Cécile

**Comment by tspmgh** [comment]
Thank you very much, i'ts is definitely helpful.
I am wondering if the supplementary materials available online as of now?
Bw

**Comment by CecileProust-Lima** [comment]
Not yet. They can be sent on demand. 
Cécile

**Comment by accole47** [comment]
Hello! I wanted to follow up on this because I initially fitted an hlme model where four classes was the best fit. We did multinomial logistic regression where class membership was the outcome and the predictors were variables that were not included in the original model. But it sounds like that's not recommended because it doesn't take the uncertainty of the latent structure into account (and our model's entropy = .70)? So since I want to retain that four class model (best fit, strong theoretical rationale) I would need to use the mpjlcmm function instead of the multinomial log regression? Only asking because it doesn't seem entirely clear when I read about the mpjlcmm function and look at the use case in the package info PDF, though I am certainly no R/stats expert. Thank you!

**Comment by VivianePhilipps** [comment]
Hello,

the mpjlcmm function can be used to link a continuous new outcome (named Yextern in the arXiv paper cited before) to the estimated latent classes. The classes would here rather be a predictor than the variable of interest. A naive method for that would be to use a linear regression with the latent class as covariate (for example with lm(Yextern ~ class) ).

If the class is your outcome, then a way to do with our package is to include your new predictors (named Xextern) in the classmb argument of the hlme function, as a mentioned is my first post on this issue.

Best,

Viviane

**Comment by CecileProust-Lima** [comment]
Hi, 
we did not add a function for computing the odds ratios. But those can be calculated easily using the estimates as exp(parm) for estimate parm. 
Cécile

**Comment by accole47** [comment]
Got it! Thank you so much!

**Comment by VSSchneider** [comment]
Hi,

Thanks so much for sharing this preprint. I would very much like to read the supplementaries if you are happy to share them.

I look for ways to relate my identified classes (identified using lcmm with threshold link function) to a binary external outcome. I am trying to understand whether I can use the mpjlcmm function for that purpose but it seems this would only work on a continuous outcome? I have already run models with predictors of the latent classes by fixing parameters as explained in previous posts. Could the same work with a binary outcome in a separate model if interested in its association with latent classes (even though modelled as a predictor)? 

I am aware the naive (3-step) approach would be to use predicted class membership in separate logistic regression models. However, I want to avoid this approach due to the classification error.

Many thanks,
Verena
