### ISSUE TITLE
class specific sigma^2 and FIML

### ISSUE THREAD

**Issue by AndreasHani** [CecileProust-Lima/lcmm#117]
Dear Cecile,

I have two general questions about the package and longitudinal data analysis:

1)	Is it possible to estimate GMM’s with class specific residual variances in lcmm?

2)	I don’t see a huge difference between FIML and normal ML-Estimation when someone has to deal with missing values in longitudinal studies. Is there some helpful literature that compares both approaches and explains the differences?

Many Thanks
Andreas

**Comment by CecileProust-Lima** [comment]
Dear Andreas, 
the package does not allow for class-specific residual variances, only class-specific Random effect variances with nwg=T. 
Regarding the FIML, my understanding is that in the context of the models estimated with lcmm package, ML and FIML are the same. 
Cécile

**Comment by jenellong-IHDP** [comment]
Hi there, 

Sorry to retread old ground. 

I would like to clarify what is meant by 
> in the context of the models estimated with lcmm package, ML and FIML are the same.


My understanding (do correct me if I am wrong) is that FIML makes use of all data, observed and missing, whilst ML only uses observed data. Hence. they are equivalent only when there is no missing values in the dataset. 

Can I confirm if ML and FIML are the same in the lcmm package even when missing values are present? 

Thank you!

**Comment by sabrishamcar** [comment]
Yes, sorry to open this up again, but I have the same question as @jenellong-IHDP . My confusion arose because even though I only have missing data in my outcome, observations are still being deleted. From previous issues, it seems that the observations with missing outcome data are supposed to be deleted, but then I am unsure of how this method is "robust" to missing data if it is still simply doing a pairwise deletion. It makes me think that it is not actually making use of all the data such as in FIML that other growth models use. Can you please clarify this? Thanks so much!

Statistical Model:
     Dataset: data_final_long_EAA
     Number of subjects: 926
     Number of observations: 2070
     Number of observations deleted: 720
     Number of latent classes: 2
     Number of parameters: 21
