### ISSUE TITLE
Interpretation of predictor coefficients 

### ISSUE THREAD

**Issue by miiroth** [CecileProust-Lima/lcmm#132]
Dear all

I am still quite new to this field and therefore I am not sure about the correct interpretation of the coefficients. 

Here what I did:
1. identify the optimal number of classes which was 4.
2. I fixed these classes (to avoid class shift) and then added a predictor to the model. 

Here my model with predictor:

m4_pred <- hlme(fCSI ~ time, mixture=~ time, random=~ 1+time, subject='CoupleID',
                  classmb =~ afMDSP_ic,
                  ng=4, data = data_long, B=Binit, posfix=FixedParms, nwg = TRUE) 

(where CSI is relationship satsisfactino, afMDSP_ic is stress)

The output now looks as follows:
Here now I am struggling on how to interpret the coefficients (e.g. what scale do they have?). Would it be correct to say "compared to class 4, class 1 is 2.06 points lower in stress"? Or would it be more a statement about probabilities of classmembership (and how exactly would this look like?)?

Thank you for answers on this relatively trivial question and best regards
Michelle

<img width="358" alt="Bildschirmfoto 2022-09-23 um 16 17 57" src="https://user-images.githubusercontent.com/113109539/191983006-4aa1535d-6dff-45b1-aae2-5127a43286e8.png">

**Comment by CecileProust-Lima** [comment]
Hi, 
your strategy of fixing the latent class model to avoid any shift is correct. For the interpretation, this is an odds ratio since this model is a multnomial logistic regression. for 1 unit increase of afMDSP, a person is more likely in class 2 than class 4, and less likely in class 1 and 3 than class 4. If you wanted to rank: the probability would be lowest in class 3, then class 1 then class 4, then class 2. To give quantification, you can use the odds-ratio exp(the parameter) which gives the odds ratio to be in the class compared to the reference class for a subject with covariate = x+1 compared to covariate equal x. 
I hope this helps
Cécile
