### ISSUE TITLE
Free variance between classes

### ISSUE THREAD

**Issue by Jezebel08** [CecileProust-Lima/lcmm#15]
Hi,
I'm running the following model to find groups in trajectories of weekly sickness absence:

Model1 <- lcmm(sum_week ~week_count, mixture= ~week_count, random = ~week_count, subject=”id”, ng=2, data=week, nwg=F, idiag=F, link=”linear”)

Where sum_week is a numeric value from 1-5 (sick-days per week), and week_count is my time variable (from week 1 to 52 doing the year).

I’m still trying to find the best model for my dataset and want to relax the between-group variance. Specifically I want to allow the variance both in the intercept and the slope factor to differ by class. However, I am not sure how to specify this using the lcmm function?

As far as I could read, the ‘nwg’ boolean does something similar by setting the covariance-variance to be proportional (or non-proportional) over classes. But I’m not sure if this will generate a model with “free” variance between classes? 

Best,
Charlotte

**Comment by CecileProust-Lima** [comment]
Hi Charlotte, 
in lcmm, you can't have a completely free variance for the random effects since it poses problems of identifiability. This is why I proposed the nwg argument to consider instead proportional variance covariance matrix. 
In addition, if I may, I understand that your outcome is ordinal with 5 different values. If so, I am not sure a model relying on the Gaussian assumption for continuous outcomes is the best. 
You might try to consider instead a model for ordinal outcomes with the link function "threshold". You should know however that the model will be a lot longer to estimate. 
Best
Cécile
