### ISSUE TITLE
Iteration process

### ISSUE THREAD

**Issue by JoaoPaulo100** [CecileProust-Lima/lcmm#16]
Dear Dr. Proust,
My data consist of 70 subjects and each has 909 weeks of mood assessments (MOOD, scale 1-6). In total, there are 63630 observations. My goal is to derive groups based on these trajectories.
I'm running the following model: 

lcmm (MOOD~ week , random = ~week , subject = 'ID', mixture = ~ week, ng = 3, idiag = TRUE, data = dataset, link="splines")

I was able to use this code on a smaller dataset. Now I have this:

“Iteration process: The program stopped abnormally. No results can be displayed“
 
Is this happening because of the number of observations? Am I choosing the wrong model or coding something wrong?

Thanks,
Joao

**Comment by CecileProust-Lima** [comment]
Dear Joao, 
I have never tried such a large number of repeated measures by individual. The way the functions are programmed may not support such structure of data. We usually have a lot more subjects than repeated measures by subjects. 
Two other comments regarding your model:
- if you have so many repeated measures, I assume this is because the dynamics is complex. But your model assumes a linear trajectory which is very strict. 
- if you have many repeated measures, maybe a random intercept and slope are not enough to capture the correlation between your repeated measures. Some Gaussian process (options cor=AR or BM) might be relevant. 
Cécile

**Comment by JoaoPaulo100** [comment]
Dear Cecile,

Thanks for the comments. I'll see what I can do about the number of repeated measures.
Regards,
Joao
