### ISSUE TITLE
Slower iteration speed for package 2.0.2 vs 1.9.5

### ISSUE THREAD

**Issue by Lrgnmllr** [CecileProust-Lima/lcmm#162]
Dear Cécile and dear Viviane,

I was running the lcmm package 1.9.5 for a while, before recently updating to package 2.0.2. I experience the new version to be significantly slower compared to 1.9.5 when running hmle, lcmm and mpjlcmm (I haven’t tested the other ones). I obtain the same results/outputs and the same number of iterations (for 1 class models at least) in both versions. When comparing the speed per iteration for 1-2 class model using hlme, I find the following:

```
Median time 1 iteration (of 100 runs)
         v.1.9.5 v.2.0.2
1-class:   1.38s   2.16s
2-class:   3.56s   5.71s
```

The model is pretty basic. For example, the 1-class model:

```
hlme(fixed = var1 ~ time + I(time^2),  random ~1, subject = “id”, ng = 1, data = lcmm_dat)
```

I am running R version 4.2.2, but it also happens on other versions (eg 4.0.4), and on other machines.
To see if the problem had to do with the packages loaded with lcmm, I saved the older version of the library containing 1.9.5, and tried the following:

```
detach(package:lcmm, unload = TRUE)
libPaths(c(“PATH_TO_v.1.9.5”, .libPaths()[2]))
library(lcmm)
```

That way, all loaded packages are the same (and the same version) as those loaded with lcmm 2.0.2. But I get the same results

The issue is probably only “visible” for bigger datasets (in my case >20000 individuals and >65000 observations), but for such data, it can mean several hours difference for more complicated models. 

I hope I am not double-posting

Any support is much appreciated 
Simon

**Comment by VivianePhilipps** [comment]
Hello Simon,

since version 2 of the lcmm package we skipped from a fortran optimization algorithm to the marqLevAlg R algorithm. This is why the current version is slower than older versions. This is the same algorithm but written in another language.
The R algorithm has the advantage to be parallelized, so you can greatly improve the running time by using multiple cores (with the nproc argument).
Our tests showed that the sequential version of marqLevALg is indeed slower than the previous fortran algorithm as you noticed, but by using 2 cores the marqLevAlg R algorithm is already faster.
You can see the simulation studies we did in the vignette of the marqLevAlg package (https://cran.r-project.org/package=marqLevAlg).

Best,

Viviane

**Comment by Lrgnmllr** [comment]
Thank you for the swift answer!
Best,
Simon
