### ISSUE TITLE
hlme lcmm classes with 0 membership

### ISSUE THREAD

**Issue by Mcgpcc** [CecileProust-Lima/lcmm#163]
Hi,
I have a query relating to instances when class membership can be 0%.  I ran hlme with ng=1..5.  The output is below, the 4 class solution is similar to the 3 class solution (& the loglik are the same).  The 5 class solution has a class with 0%.  As per a previous closed query, the reason could be that may converge to local maxima which correspond to the solution with a smaller number of latent classes, and in that case, some classes may have 0 members.  
Is it acceptable to choose the 3 class model below, or does this 0% membership indicate problems for the potential solution.

Many Thanks

        | G | loglik | conv | npm | AIC | BIC | SABIC | entropy | ICL

m71 | 1 | -6931.876 | 1 | 6 | 13875.75 | 13907.53 | 13888.47 | 1 | 13907.53
m72a | 2 | -6825.31 | 1 | 9 | 13668.62 | 13716.29 | 13687.7 | 0.7227235 | 11008.18
m73a | 3 | -6773.001 | 1 | 12 | 13570 | 13633.56 | 13595.44 | 0.6577791 | 11143.12
m74a | 4 | -6773.001 | 1 | 15 | 13576 | 13655.45 | 13607.8 | 0.550421 | 11641.86
m75a | 5 | -6761.508 | 1 | 18 | 13559.02 | 13654.35 | 13597.17 | 0.5900258 | 11652.24

       | %class1 | %class2 | %class3 | %class4 | %class5 |  
m71 | 100 |   |   |   |   |  
m72a | 54.23729 | 45.76271 |   |   |   |  
m73a | 36.67797 | 29.28814 | 34.0339 |   |   |  
m74a | 0 | 36.67797 | 29.28814 | 34.033898 |   |  
m75a | 36.13559 | 0 | 29.69492 | 2.440678 | 31.72881 |

**Comment by VivianePhilipps** [comment]
Hi,

the m74a model is actually a 3 class model and is the same as m73a. In the same way, m75a is a 4 class solution because one class is empty.
To fairly compare them, you should run a 4 class model with parameters from the m75a model without the 3 coefficients corresponding to the second class (the empty class). So the criteria, for example the BIC, will be computed with the 15 relevant parameters instead of 18 (where 3 parameters are not useful).
To do so, create a vector of initial values and put it in the B argument :
` Binit <- m75a$best[-c(2,6,11)] # I suppose here that the 3 parameters related to the empty class are the 2nd, the 6th and the 11th, but this is to adapt`
` m74b <- hlme(..., ng=4, B=Binit)  # should give a 4 class model with loglik=-6761.508`
`summarytable(m71, m72a, m73a, m74b)
`

Viviane
