### ISSUE TITLE
Empty score test result using jointlcmm function

### ISSUE THREAD

**Issue by wy2020hku** [CecileProust-Lima/lcmm#178]
Dear Cécile and Viviane,

Thank you very much for the great lcmm package and consistent help to answer questions!
I have encountered a problem that the result model (from jointlcmm) doesn't provide the score test result (i.e. there is no score test result below the obtained BIC):

Part of the model summary:

> Goodness-of-fit statistics: 
>      maximum log-likelihood: -343326.45  
>      AIC: 686724.89  
>      BIC: 687029.45  
>  
>  
> Maximum Likelihood Estimates: 
>  
> Fixed effects in the class-membership model:
> (the class of reference is the last class) 

It is my first time to have this case as the previous models always have the score test result, either significant or insignificant, as long as the model successfully converge.
Appreciate a lot if you know the reason!

Best,
Yuan

**Comment by VivianePhilipps** [comment]
Hi,

the score test results are only printed if they are available. It seems here that the computation of the test statistic went wrong (m$scoretest is NA), but it is difficult to say why.
You can run again the model with the parameters you obtained as initial values (argument B=m$best in the Jointlcmm function), hopping that the computation will be fine this time. Otherwise we can't act much on this test.

Best,

Viviane

**Comment by wy2020hku** [comment]
Hi Viviane,

Thank you for your suggestion. I can usually get valid test result after running again the models.

Best,
Yuan
