### ISSUE TITLE
Difficulty in Correctly Identifying Trajectories with multlcmm

### ISSUE THREAD

**Issue by nuria17** [CecileProust-Lima/lcmm#204]
Dear developers,

We are currently working with a toy dataset that contains two outcome variables (y1 and y2) with repeated measurements, and we are interested in modeling these outcomes according to age. The dataset already includes well-defined trajectories, each with a low residual standard deviation.

<p float="left">
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/08ecd56d-aaca-4da1-bec8-e5c8b2e35fe4" width=48% height=45%>
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/2a069bf7-6af7-4242-94b3-03fba2157456" width=48% height=45%>
</p>

Our initial approach was to use a multivariate latent class mixed model for multivariate outcomes (multlcmm) since we assume that both outcomes are measuring the same underlying latent classes. Specifically, we know that there are 5 trajectories, each with the same number of individuals. These trajectories exhibit different intercepts or slopes for y1, while two of them share the same intercept and slope for y2.

Here is the code we used for the multlcmm model:

```
model_init = multlcmm(fixed=y1+y2~1+age,random=~1+age, 
subject='id',data=data)

model_traj = gridsearch(rep=5, maxiter=100, minit=model_init,
                        m=multlcmm(fixed=y1+y2~1+age,
                        random=~1+age,
                        subject='id',
                        link=c('linear'),
                        ng=5,
                        data=data,
                        mixture=~1+age, 
                        verbose=TRUE))

```
<p float="left">
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/9c14c6ba-4049-43a8-b6b7-d440c807103a" width=48% height=45%>
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/bcc35db4-5498-45ce-bb22-f24b6cfafef7" width=48% height=45%>
</p>

However, when using this model, we noticed that individuals were assigned to only three out of the five trajectories. These three trajectories matched with the observed data in y2 but not in y1. To address this issue, we attempted to include an outcome-specific intercept using the randomY=TRUE parameter as follows:

```
model_init = multlcmm(fixed=y1+y2~1+age,random=~1+age, 
subject='id',randomY=TRUE,data=data)

model_traj = gridsearch(rep=5, maxiter=100, minit=model_init,
                        m=multlcmm(fixed=y1+y2~1+age,
                        random=~1+age,
                        subject='id',
                        link=c('linear'),
                        ng=5,
                        data=data,
                        randomY=TRUE,
                        mixture=~1+age, 
                        verbose=TRUE))

```
<p float="left">
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/00e8d818-7c42-42c2-a95c-5ffae398f962" width=48% height=45%>
  <img src="https://github.com/CecileProust-Lima/lcmm/assets/44896841/b3fecb37-e136-4d43-9e9e-c26953677d6d" width=48% height=45%>
</p>

With this modification, we obtained five trajectories that perfectly fit the observed values in y1 but not in y2.

The only way we were able to correctly detect the five trajectories for both y1 and y2 was by using the mpjlcmm routine. We initially fit two separate hlme models for y1 and y2 and then performed the optimization through mpjlcmm. However, we are uncertain if this is the most appropriate approach, and we would like to understand the differences between multlcmm and mpjlcmm.

Thank you very much for your assistance.

Best regards,

Núria

**Comment by VivianePhilipps** [comment]
Hi,

if you are using multlcmm, you make the assumption that both outcome measure the same process. This is a strong assumption, but I understand that to your opinion it holds on your data.
In mpjlcmm, you assume that you are modelling 2 different processes and that they are not correlated (the total random effects variance matrix is block-diagonal). The only link between the 2 outcomes is the latent class. You can check that if you estimate a mpjlcmm model with 1 class, you get the same results as if you estimate 2 hlme models separately. 

By the way, if you check the fit of a mixed effects model, I suggest to use the subject-specific predictions (plot(.., which=)"fit", marg=FALSE)) rather than the marginal predictions. We expect that the subject-specific predictions are close to the observations, but the marginal prediction are often outside the confidence interval because we miss a part of the model, we miss the random effects.

Best,

Viviane
