### ISSUE TITLE
LCMM error

### ISSUE THREAD

**Issue by pitina244** [CecileProust-Lima/lcmm#220]
Hi,

I am running my model using all different link functions
LCMMmodel <- lcmm(myout ~ age + sex + educ + myoutbaseline, random=~ year, subject='IID', data=mydata)
HLMEmodel <- hlme(myout ~ age + sex + educ + myoutbaseline, random=~ year, subject='IID', data=mydata)
SPLINESmodel <- lcmm(myout ~ age + sex + educ + myoutbaseline, random=~ year, subject='IID', data=mydata, link='5-quant-splines')

and only lcmm has an error

 Numerical problem by computing fn 
          value of function is : NaN 

Would appreciate any suggestions on what is wrong/how to fix!

thanks in advance

**Comment by VivianePhilipps** [comment]
Hi,

this message indicates an internal computation issue. This is usually fixed by specifying different initial values in argument B.
To see the default initial values, you can run for example
 ` lcmm(myout ~ age + sex + educ + myoutbaseline, random=~ year, subject='IID', data=mydata, maxiter=0)$best`

And then, give in B a slightly different vector of initial values
 `m <- lcmm(myout ~ age + sex + educ + myoutbaseline, random=~ year, subject='IID', data=mydata, B=c(...))`

Viviane

**Comment by phoebesco** [comment]
Thank you!
