### ISSUE TITLE
Leading minor is not positive definite

### ISSUE THREAD

**Issue by watson-c** [CecileProust-Lima/lcmm#24]
Dear Dr Proust-Lima,

Thank you so much for creating this package - it has been well used!

I'm currently running a quadratic model with 2-4 time points per individual (approx 72000) and various subsets keep crashing while others run, despite having the exact same code.

The error message is "Error in chol.default(vbb) : the leading minor of order xx is not positive definite" .  Do you have any advice on how to fix this? 

Many thanks,

Charlotte

**Comment by CecileProust-Lima** [comment]
Dear Charlotte, 
I am sorry, I don't see what happens here ... what is the function used please?
Cécile

**Comment by watson-c** [comment]
Dear Cecile,
It occurs when using the gridsearch function to run multiple start points, but only occasionally. I have looked back through the source code but unfortunately haven't been able to identify where my data/code might have gone wrong.
Charlotte

**Comment by CecileProust-Lima** [comment]
Thank you. This intervenes in the generation of random initial values: vbb is the variance covariance matrix of the parameters under G=1 model. Maybe the convergence of this model was limit. Try maybe to change the order (metric) of some parameters like time variable used in the random statement. Too large times (in days instead of months or years for instance) usually cause problems of convergence. This might help. 
Cécile

**Comment by watson-c** [comment]
Dear Cecile,
Thank you very much for your help - changing the convergence parameters fixed it (time variables were already as small as could be).
Charlotte
