### ISSUE TITLE
strange results in hlme()

### ISSUE THREAD

**Issue by mattkumar** [CecileProust-Lima/lcmm#26]
Hello,

I am attempting to fit a series of latent class growth models using the hlme() function and am observing some strange results.  Unfortunately, I can't provide the data nor the output due to work restrictions, however I hope I can at least describe my setup.

Sample Size = ~3000 patients
Time = Measured in Months (Values range from -24 to 24)
Outcome = A continuous measure, which ranges from 0 to 14.

Each patient has a variable number of time points at which the outcome was measured. The time points can be unique to a patient too (e.g. patient A has -4, 3, 5, patient B has -14, -12, -4, 5, 20).
 
I'm attempting to fit the model using this syntax:

model1 <- hlme(data=foo, outcome ~ time + time_squared, random=~time + time_squared, mixture=~time+time_squared, id='id', ng=3)

I vary ng from 2 to 4. Time_squared is a quadratic time variable I've created. I believe the way I have specified this model is equivalent to poly(time, degree=2, raw=TRUE)

The issue comes about when I look at the results for the fixed effects. If I specify, say ng=3, and look at the fixed effects for the longitudinal model, I see that the intercept, slope, and quadratic terms are identical for latent class 1 and 2, while class 3 has unique estimates.  This also happens for ng=2, and ng=4. I'm wondering what this indicates? Is it a local maxima issue? I have tried to use gridsearch, and specify initial starting values using the approach in the paper for your package to no avail. If I remove the random effect for slopes, and re-run the model, I get unique estimates (e.g. each latent class has a different intercept and slope in the fixed effects part)

e.g.

model2<- hlme(data=foo, outcome ~ time + time_squared, random=~1, mixture=~time+time_squared, id='id', ng=3)

Any insight is appreciated.
Best,

**Comment by CecileProust-Lima** [comment]
Dear Matthew, 
thank you for your comment. Your problem is indeed a problem of local maximum. It seems that you converge to a 2 class solution (1+2 being one unique class, and 3). This happens sometimes and my advice would have been to use gridsearch (maybe try more replicates and more iterations). Or maybe you don't have any heterogeneity more than 2 classes (this is unlikely - not seen so much in the past but might be possible). 
Other solutions could be to specify yourself the B vector. This is not a nice solution but often useful. 
Have you tried to estimate the 2 class model from the estimates of (1/2, and 3)? That should give you the same likelihood as your 3 class local maximum. 
Maybe changing the unit of time might help  ... this is usually more relevant when you have convergence issue, but it is worth a try. 
I hope this will help,
Cécile
