### ISSUE TITLE
categorical or numeric time points and LSmeans

### ISSUE THREAD

**Issue by BochaoJ** [CecileProust-Lima/lcmm#27]
Dear Prof. Cécile and your team,

I am using LCMM package to classify the patients based on their trajectory patterns. The outcome is continuous variable and we do not want to consider any covariate except the time (week: 0,1,2,4,8,12,16,20,24). The question is " does the week in our model can considered as numeric or catergorical ?" 

lcmm.fit<-hlme(outcome~week,random=~week,mixture=~week,subject="ID",data=dataset,ng=3)

Another question is could we report the LSmeans at each time point for each identified subgroups? In MMRM method, we have the option to report the LSmean but MMRM consider the time point as categorical data, so I wonder if this LCMM can have the same option to report the LSmean?  Thanks a lot.

Best wishes,
Bochao Jia

**Comment by VivianePhilipps** [comment]
Hello,

in the model you mentioned, the time variable is treated as a numeric variable, and you consider a linear trajectory. You can also specify it as a factor (~ factor(week)), so it will be categorical. You will then estimate one parameter for each time point, instead of one parameter for the whole trajectory.

The package does not have any LSmean option. You can compute them by hand, and if you need to test a combination of parameters you can use the WaldMult function.

Best,

Viviane
