### ISSUE TITLE
should dvs in a class always be related to a latent variable in the same direction

### ISSUE THREAD

**Issue by henkvs** [CecileProust-Lima/lcmm#277]
Dear Cecile,

I am running a multlcmm on variables that are negatively related to each other, e.g. negative affect become larger with time and positive affect become smaller with time. When I run a multlcmm (just with ng  = 1), the model seems not to converge and when I plot the trajectories with predictY both DVs show the same (not the opposite) pattern over time, the Y-value just has different scales.

When I repeat the multlcmm in a univariate way, just with negative affect and positive affect as the dv in separate models, the models do show the proper (opposite) change over time.

It does not matter whether time is a factor, a linear variable, or a poly. The behavior is always the same.

Is the relationship between dvs and the latent variables perhaps constrained so that the relationship between all dvs and the latent factor for a given cluster is always only allowed to be in the same direction? If so, is this behavior on purpose and how can I still run multivariate cluster analyses on my data set? 

Thank you very much for your help!

Best, Henk

**Comment by VivianePhilipps** [comment]
Hi Henk,

the multlcmm function assumes that all variables go in the same direction. 
To use the function with two negatively correlated variables, you will have to reverse the coding of one variable so that the hypothesis holds. I know this can be disturbing for the interpretation, but the modelling will be fine that way.

Best,

Viviane

**Comment by henkvs** [comment]
Thank you very much Viviane!
