### ISSUE TITLE
How to account for individually-varying times of measurement?

### ISSUE THREAD

**Issue by jenellong-IHDP** [CecileProust-Lima/lcmm#284]
Hello, 

Thank you for making this package open-source. I am new to latent class modeling and it has been very helpful. 

My dataset contains longitudinal measurements with individually-varying times of measurement. For example, measurements intended for a post-natal week 24 stage may not necessarily occur exactly at week 24 for all participants due to logistical exigencies (e.g. some participants will be measured at week 23, some at week 25). 

I understand that in such cases, it is [important to account for individually varying times of measurement within waves](https://doi.org/10.1080/10705511.2016.1247646). van de Schoot et al. (2016; linked above) recommended that these individually-varying times of measurement should be incorporated into the model's random effects. 

Kindly advise on how to implement this in lcmm?

In my current dataset, I have recorded the intended measurement timepoint under the variable `timepoint`, as well as the actual weeks from childbirth for each observation under the variable `t_cbrth` (0 is set to the child's date of birth, negative values indicate prenatal timepoints and positive values indicate postnatal timepoints). 

My questions are thus: 
1. Should I fit the model using `timepoint` or `t_cbrth` as the predictor in the fixed effects? 
2. If I specify `timepoint` as the predictor for fixed effects, should I additionally specify `t_cbrth` as a covariate, random effect, or both? 
3. If I specify 't_cbrth' as the predictor for fixed effects, do I still need to specify it as a random effect?

Thank you very much.

**Comment by VivianePhilipps** [comment]
Hello,

it is better and more precise to use to actual time rather than the intended measurement time when possible. 
The "timepoint" variable would be chosen if the model needs a discrete time scale or needs that all subjects are measured at the same time. Here, the mixed models can deal with different measurement times between subjects, so the "t-cbrth" variable is preferable.
You can't use both since they provide almost the same information, "timepoint" being an approximation of "t_cbrth".

Specifying the time variable only in the fixed part or in fixed and random does not depend on which variable is used, but it depends on the flexibility you want to give to the model.
If you put the time variable only in the fixed effects, you make the assumption that all the subjects have the same evolution with time.  If you specify it also in the random part, you will estimate a mean trajectory and a specific deviation from this mean for each subject. So you will have a specific trajectory for each subject. 


Best,

Viviane

**Comment by jenellong-IHDP** [comment]
Thank you so much, that was very helpful!
