### ISSUE TITLE
How best link function is chosen in vignette lcmm

### ISSUE THREAD

**Issue by jenellong-IHDP** [CecileProust-Lima/lcmm#286]
Hello, 

I have been following the `lcmm()`  vignette to understand how to select the best link function, as I am not familiar with them. 

I understand that we should try out different link functions using one-class models and select the link function that gives the lowest AIC. 

In the [vignette](https://cecileproust-lima.github.io/lcmm/articles/latent_process_model_with_lcmm.html#select-the-best-model), the 5-quant-splines function is stated to "provide the best fit according to the AIC criterion." However, in the vignette, the 5-quant-splines function has a larger AIC than the beta function: 

```
summarytable(mlin,mbeta,mspl,mspl5q,which = c("loglik", "conv", "npm", "AIC"))
          loglik conv npm      AIC
mlin   -7056.652    1   8 14129.30
mbeta  -6306.962    1  10 12633.92
mspl   -6509.681    1  13 13045.36
mspl5q -6320.085    1  13 12666.17
```

May I ask why the beta function was not considered the best function despite having the lowest AIC? 

Thank you!

**Comment by jenellong-IHDP** [comment]
As an additional question, I would like to ask if it is ever acceptable to choose a link function that doesn't have the lowest AIC? 

In my analysis, the model with 8-quant-splines has the lowest AIC: 
```
         npm conv      AIC      BIC
m_linear   6    1 29027.78 29058.47
m_beta     8    1 28220.80 28261.73
m_3qs      9    1 28369.70 28415.74
m_4qs     10    1 28208.73 28259.89
m_5qs     11    1 28176.23 28232.51
m_6qs     12    1 28130.08 28191.47
m_7qs     13    1 28083.55 28150.07
m_8qs     14    1 28081.79 28153.42
```
After plotting the link functions as recommended in #154, I find that they are very similar: 

![link_functions](https://github.com/user-attachments/assets/3f40993e-5cb2-430f-8031-1105f91ef2ec)
 
The 8-quant-splines model has a large number of parameters, but is very close to the other spline functions. Would it be appropriate to reject the 8-quant-splines link function and instead choose the 5-quant-splines link function on the grounds of parsimony, even though it doesn't have the best AIC?

Thank you.

**Comment by VivianePhilipps** [comment]
Hello,

it is true that in the vignette the beta link has better AIC, but we rarely use it. We show it for illustration but the splines are much more flexible without adding too much parameters (1 more parameter than the beta with the minimal number of nodes). Here, the model with "5-quant-splines" has better AIC among the splines models, that's why we used it.
In general, the AIC is one criterion for choosing the link function, but the other criterion is the estimability of the model. With too many parameters, you will reach convergence with difficulty. In your plot, the four splines links are very close, so you could choose the more parsimonious one.

Best,

Viviane

**Comment by jenellong-IHDP** [comment]
Understood Viviane, thanks so much!
