### ISSUE TITLE
hlme: argument subject numeric

### ISSUE THREAD

**Issue by ericshiroma** [CecileProust-Lima/lcmm#29]
Version 1.8.1

bmi_long from LCTMtools
------
data(bmi_long)
bmi_long$id <- as.numeric(bmi_long$id)
model1 <- lcmm::hlme(fixed=bmi~1+age+I(age^2),
                   mixture = ~1+age+I(age^2),
                   random=~-1,
                   ng=5,
                   nwg=FALSE, data=bmi_long[1:200,],
                   subject="id")
---
Error in lcmm::hlme(fixed = bmi ~ 1 + age + I(age^2), mixture = ~1 + age + : The argument subject must be numeric
-------
 class(bmi_long$id)
[1] "numeric"
----
issue replicated with 2 other datasets

**Comment by jrmie** [comment]
I also got this error some days ago. 
Functions of the lcmm package check the subject argument with `if(!is.numeric(data[,subject]))`
With my R session the problem came from the tidyverse package I guess. Something go wrong with data frame which has "tibble", "tbl", or "tbl_df" classes

```
> is.numeric(bmi_long[,"age"])
[1] TRUE
> library(tidyverse)
> is.numeric(bmi_long[,"age"])
[1] FALSE
```

Using `as.data.frame()` function before call a function from `lcmm::` fixed the issue

```
> class(bmi_long)
[1] "tbl_df"     "tbl"        "data.frame"
> bmi_long <- as.data.frame(bmi_long)
> class(bmi_long)
[1] "data.frame"
> is.numeric(bmi_long[,"age"])
[1] TRUE
```

**Comment by CecileProust-Lima** [comment]
Thank you for your feedbacks. We will correct that in the next version. 
Cécile
