### ISSUE TITLE
can not fix the parameters in variance-covariance matrix 

### ISSUE THREAD

**Issue by Adib-Makrooni** [CecileProust-Lima/lcmm#42]
It seems that we can use the argument "posfix" to fix some parameters at a specified value, but when the variance-covariance matrix is NON-diagonal this argument does not work (the parameters will still be estimated in the matrix). Could you please let me know what to do in this case?

**Comment by VivianePhilipps** [comment]
Hi,

to estimate the variance-covariance matrix of the random effects, we use the cholesky parametrization, and the posfix argument will in fact fix a cholesky parameter instead of a covariance parameter. This is generally not equivalent.
It should be possible to fix any covariance by constraining some cholesky parameters, but this is not yet included in the lcmm package.

Viviane
