### ISSUE TITLE
lcmm package with 5classes

### ISSUE THREAD

**Issue by cheteuwabo** [CecileProust-Lima/lcmm#45]
hello Ms cecile, i am a student in nutrition and.food hygiene.
I am working on diet trajectories using lcmm package in R . I came accross your paper "Estimation of Extended Mixed Models Using Latent
Classes and Latent Processes: The R Package lcmm 
" and a website where you described the analysis  lcmm V1.7.8 on cran · CecileProust-Lima/lcmm@a79e70b
which has helped me to understand the analysis  process. 
 i followed the steps. as described in "Estimation of Extended Mixed Models Using Latent
Classes and Latent Processes: The R Package lcmm " but i still encountered many issues which are:

1－i want to generate 5 number of classes of diet , all the models i have tried so far are not convergent when i summarise the models ,  percentages in some classes are NA  and i only get one straight line when i plot the model.

2－ When i try three classes  the model is convergent but the number of classes to be generated  according to the litterature is 5 just like BMI in your paper.

I AM ASKING MYSELF WHAT COULD BE PROBLEM? I WILL APPRECIATE IF YOU CAN GIVE ME SUGGESTIONS ABOUT IT.
THANK YOU.

SINCERLY YOURS

**Comment by CecileProust-Lima** [comment]
Hi, 
I don't know if the comment is too late. Convergence towards a smaller number of groups is usual, this might be due to: 
- a local maximum: be sure you use gridsearch to scan all the parameter space. There is a vignette on that in the package;
- the specification of the model: maybe you specified a trajectory with time which is not flexible enough (if you have straight lines, you must have specified that). Alternatives are polynomials, natural splines (function ns of splines package) or any (multivariate) function of time. 
- the data : maybe you don't have enough information in your data or a population which is different from the assumptions from the literature. 
I hope you will find a solution. 
Just to inform you, there is a new lcmm version on cran, version 1.9.1. 
Best
Cécile
