### ISSUE TITLE
Questions about lcmm()

### ISSUE THREAD

**Issue by anabravocastillo** [CecileProust-Lima/lcmm#46]
Dear Dr. Proust-Lima and lcmm-team,

I am a doctoral student in the psychology department of the University of Córdoba (Spain).
First of all, thank you for creating this wonderful R package and secondly for all examples, feedback and help that you and your lcmm team offer us.
Secondly, I would like to use the R lcmm package to find trajectory classes in longitudinal data with 4 repeated structured measurement time points (every 6 months) of high school student victimization levels (N = 734). Victimization levels for each wave was calculated as follows: Students were asked about who victims are in their class. The number of nominations received by each student was counted, divided by the number of possible nominators to account for differences in classroom size. Proportional scores for each student were calculated by class. The victimization score ranges from -1.14 to 5.20, and is a continuous variable. One of **my questions** is related to this: Should I transform the negative score into positive?

On the other hand, since victimization is a score with a non-Gaussian distribution, I fit a mixed model of latent process (lcmm function). At this point I would like to show you my script because I have doubts about whether I have written it correctly, because my time variable is computed as time 1 = 0; time 2 = 1; time 3 = 2; time 4 = 3. and I'm not sure if I can use it as I did:

linear1 <- lcmm (z_score_vict ~ Time, random = ~ -1, subject = 'student_ID', data = Variables) 
splines1 <- lcmm (z_score_vict ~ Time, random = ~ -1, subject = 'student_ID', data = Variables, link = "splines")

Finally, following other examples that you offer, I have chosen the splines model as the best option to fit the next model with ng with k-classes. However, I do not understand what the exact meaning of this kind of analysis is. I have looked up on Internet but I cannot find anything to help me understand what exactly "splines" calculations mean.

Thank you very much for your support!
Kind regards, 
Ana

**Comment by CecileProust-Lima** [comment]
Hi, 
regarding your analysis, 
- lcmm handles Y that are negative
- the splines link function is one type of link function that normalizes your Y so that you can fit a linear regression on the normalized scale. This is done internally. Please look at the vignettes on pre-transformation and lcmm for this. 
- time function. If the Time variable is numeric, the program will assume a linear trend according to your variable. If you want a nonlinear trend with time, you can include in fixed some functions of your variable Time
I take advantage of this response to inform you that a new version of lcmm is available on cran, version 1.9.1. 
Best
Cécile
