### ISSUE TITLE
predictY

### ISSUE THREAD

**Issue by pietro2204** [CecileProust-Lima/lcmm#58]
Hi - I am using the ‘hlme' function in R to model intakes of alcohol at different ages within individuals, very handy indeed.
As I have multi-center data, have included 'country' in the fixed part of the model. Two points:
- Is the choice justified, or are there more sensible ways to account for country? 
- in an attempt to compare predicted values of country-adjusted models with unadjusted ones, I had the  impression that the 'predictY' function does not work with factor variables. 

Any help would be much appreciated. Thank you in advance. Pietro

**Comment by VivianePhilipps** [comment]
Hello Pietro,

If you have multi-center longitudinal data, you may need two levels of random effects (centers and individuals), but our package does not deal with this kind of data. Other packages estimating mixed models are available for that.

Concerning the predictY function, several problems have been reported with factor variables.
Even if the variable is already declared as a factor in your dataset, you can try to enter it explicitly as a factor in the formula (for example with fixed=Y~Time*factor(X)). 
The best solution would be to enter multiple dummy variables instead of one variable with multiple categories, so you no longer use factors.

Thank you for your feedback,

Viviane

**Comment by pietro2204** [comment]
Hi Viviane,

would a strategy that defines latent classed in hlme (no adjustment for country), and derives class-specific longitudinal models with subject and country random effects  read sensible to you?  
And yes, I am now swapping to dummy variables. 

Thank you for your quick help. Pietro
