### ISSUE TITLE
Missing data and multiple imputation with LCMM

### ISSUE THREAD

**Issue by edwinadrianta** [CecileProust-Lima/lcmm#70]
Dear Cecile,

I currently develop a growth mixture model by using the 'hlme' function from the 'lcmm' package. However, I have missing data and my colleagues suggested me to do a multiple imputation. As a consequence, I have 40 datasets to analyse. I have an enquiry regarding the lcmm package:

(1) Is there a way for us to have a pooled result instead of individually analysing the 40 datasets?
(2) Alternatively, is it possible to fit the model with Full Information Maximum Likelihood?

Thank you so much for your kind help in developing this useful package.

yours,
Edwin

**Comment by CecileProust-Lima** [comment]
Dear Edwin, 
lcmm handles missing data on the endogenous data (i.e., the dependent variables) as it relies on maximum likelihood but it does not handle missing data on the exogenous data (i.e., the covariates on the right-hand side of the formulas) since they are not directly modeled. 
If you want to account for missing data on the covariates, multiple imputation is an option. However, you will have to summarize the estimations yourself. In a classical context, this is not complicated, you only need to have the estimates of each dataset 
coef(m) and their variance matrix vcov(m) (where m is the object). 
The problem with a mixture model is that you might have different labeling of the classes. Probably you will have to inspect that manually, and do some permutation if needed (function permut in the package). 
Good luck!
Cécile

**Comment by edwinadrianta** [comment]
Dear Cecile,

Well noted. Thank you for the response and insight.

yours,
Edwin
