### ISSUE TITLE
Gap in plot, Time variable and splines

### ISSUE THREAD

**Issue by amberntsson** [CecileProust-Lima/lcmm#78]
I´m modeling childhood growth - where I have the children´s BMI (non-Gaussian) measured at 1 month, 3 months, 6 months, 9 months, 12 months, 18 months and 24 months. 
![image](https://user-images.githubusercontent.com/43166642/120269479-31c1a280-c2a8-11eb-86e2-307c3200f3fe.png)

I have used the code below for modeling and exploring different growth patterns. 
gmm1<- lcmm(bmi ~ age+I(age^2), subject="id", random =~ age+I(age^2), ng=1, data=growthData)
gmm2<- gridsearch(rep=100, maxiter=30, minit=gmm1, lcmm(bmi ~ age+I(age^2), subject="id", random =~ age+I(age^2), ng=2, data=growthData, mixture =~ age+I(age^2), nwg=TRUE))
gmm3<- gridsearch(rep=100, maxiter=30, minit=gmm1, lcmm(bmi ~ age+I(age^2), subject="id", random =~ age+I(age^2), ng=3, data=growthData, mixture =~ age+I(age^2), nwg=TRUE))

I have run the lcmm with my Time variable (age) as I just described (coded 1, 3, 6, 9, 12, 18, 24) and it converges without issues. However, when I´m plotting the predicted vs observed values, there is always a gap in the slope.
![image](https://user-images.githubusercontent.com/43166642/120270390-d1cbfb80-c2a9-11eb-9d81-ccb5c3ce0983.png)

That´s why I´m thinking that it could be a problem with the coding of the age variable. 
**Should my first time point (1 month) be coded as 0 and the rest time points be coded as 1, 2, 3, 4, 5, 6? Or can I keep my time variable as it is? Or what else could be causing this gap?**

Also, as you can see, the predictions does not provide a good fit of the model. I tried to run the code with manual splines added to improve the fit of the model, as the slope is strongly curved during the first 12 months and not so curved the rest 12 months. I tried the following coding:
gmm1<- lcmm(bmi ~ age+I(age^2), subject="id", random =~ age+I(age^2), ng=1, data=growthData, link="5-manual-splines", intnodes=c(6, 9, 12))
I get the error message "Intnodes are not inside the boundaries of the marker". I thought I was supposed to enter the ages where I wanted the nodes (6, 9 and 12 months), but obviously I don´t get how to enter the splines correctly. **How do I add splines to my current code?** 

Thank you!!

**Comment by CecileProust-Lima** [comment]
Hi, 
regarding the plot which displays the observations versus predictions; the lines report the average of the observations within each interval. If you do not have observations in an interval, then the function cannot report the average. You could change the intervals you want to use in the plot using break.times argument so that you have information within each interval.

Regarding the timescale, you should keep it as it is in reality: 1, 3, 6, 9, 12, 18, 24. i would also recommend using the exact individual times when available. Regarding the baseline, I don't see any problem having all the data from 1 and not 0. you should just keep in mind that the interpretation of the intercept and simple effects (not in interaction with time) are done for time=0. If you want them to be at time=1 then, just consider time-1. 
Finally, be careful, the splines option is not with regards to the time but the Y transformation. Look at the vignettes and paper for that. If you want splines on time, then you should include them in the fixed= part and random= part by replacing the age and age^2. 

Good luck with your analyses
Cécile
