### ISSUE TITLE
Convergence criteria fixed at an unique value

### ISSUE THREAD

**Issue by BenjamLandre** [CecileProust-Lima/lcmm#8]
I’m working with repeated measures (n~ 14300, ~20 time points). 
I'm trying to use latent class mixed model to describe evolution of a continuous marker (body mass index) according to age (age + age² + cohort effect (binary) ).

I have some convergence issues related to the “derivative” criterion which take the value 1.01 for every model tested for now.

I’ve tried several things:
Tested several initial B values, 
increased rep and niter values, 
split my data and run the model in each part to locate a possible error in data. 

The derivative criterion is always 1.01.

Any idea where i can look for?

Thanks,

```
##
DATA$age <- DATA$age – 40 #minimal value
DATA$age_squared <- DATA$age * DATA$age
M1 <- hlme(fixed = BMI ~ age + age_squared + c_effect ,
            random = ~ age + age_squared, subject = "PROJ_GEST_NTT",
            data = DATA[,])

M2_Hcc<- gridsearch(hlme(fixed = BMI ~ age + age_squared + c_effect,
                        random = ~ age + age_squared, subject = "PROJ_GEST_NTT",
                        data = DATA[,], 
ng=2, 
mixture=~ age + age_squared), 
rep = 200, maxiter = 20, 
minit = M1)
```

**Comment by CecileProust-Lima** [comment]
The "derivative" criterion is the most important convergence criterion. It is based on both the first derivatives and the inverse of the matrix of the second derivatives. It ensures that the program converges at a maximum.

When it can't be computed correctly, the program gives the value = 1+threshold where threshold was given in input or by default (0.0001). In your case, it was 0.01 since the model which did not converge is the the pre-gridsearch model with G=1). 

There are several reasons that may induce a non convergence, e.g.:
- when the time variable (or more generally a variable with random effects) is in a small unit which induces too small associated parameters (for instance days). In that case, changing the scale (for instance with months or years) may solve the problem. 
- in models with splines in the link function (lcmm, multlcmm, jointlcmm) or with splines in the baseline risk function (jointlcmm), a parameter associated with splines very close to zero may prevent for correct convergence as it is at the border of the parameter space. In that case, this parameter can be fixed to 0 and convergence should be reached immediately. 
- when the data are not rich enough and/or the model is too complicated. In that case, this is a problem of numerical non identifiability. There are not many solutions (other than simplifying the model) but some directions may be: 
     - be patient, it happens that after some iterations the derivatives might be inversible and the model converges (you can change maxiter or rerun the program from the estimates at the non convergence point); 
     - you can try to assume a less stringent threshold (e.g., 0.01) but be careful, convergence might be of lower quality;
     - run the model from different initial values. 

ANYWAY ! In your case, the problem possibly comes from another reason. You created variables outside the dataset (age and age_squared) so I don't think the function understands them. You should create the new variables within the dataset: 

DATA$age <- DATA$age – 40 #minimal value
DATA$age_squared <- DATA$age * DATA$age

Cécile

**Comment by BenjamLandre** [comment]
Thanks for your reply Cécile,
The variable creation error is a typing mistake in the previous post (edited).

The time variable (age) is expressed in year and rounded to the closest integer value. 
Therefore individuals may have up to two values associated with one age.
I will try with age rounded with more precision.
Analysis are conducted separately in men and women. Only men sample has this issue. 
I will try to test a men k cluster model with initial values from the women k cluster model.
