### ISSUE TITLE
Question on vignette regarding transforming age variable

### ISSUE THREAD

**Issue by fcudhea** [CecileProust-Lima/lcmm#88]
Hello,

In your very helpful vignette where you illustrate how to use the lcmm package (https://cran.r-project.org/web/packages/lcmm/vignettes/latent_class_model_with_hlme.html), you mention re-centering and scaling the age variable to avoid numerical issues: "paquid$age65 <- (paquid$age - 65)/10"

My question is, how did you decide on the values 65 and 10? Is there a specific protocol  / "correct way" that ought to be followed for transforming the age variable, or is any choice of values, as long as it helps avoid computation issues, ok?

Thank you for your time and your work on this package.

**Comment by CecileProust-Lima** [comment]
Hi, 
we chose to use a recentering because we are studying older adults (with age >=65). If we had kept age, the intercept of the model would have been interpreted for an age=0 (so at birth) which does not have any meaning in our sample of elderly. We thus chose to recenter to 65 with age65 = age- 65 to ensure a better interpretation of the results when our timescale equals 0, that is age65=0 so age=65. 
For the rescaling, this is a recurrent problem in linear mixed models: the timescale always need to be scaled so that the parameters are not too big and not too close to zero. With age (in years) then if you add an age^2, you may have so big values that the associated parameter may be very small (even though it is relevant / significant). And if you estimate the variance of a random-effect on this age^2, then the variance is even smaller. To avoid this and keep parameters to estimate not too close to 0 because of a bad scaling, we specify age in decades. 
I hope this will help you decide what parameterization of your timescale is the most relevant. One last advice, when recentering / rescaling, don't forget about the interpretation. For us, 65 years old was the minimum age so we were happy having interpretation at that age, and interpreting in decades or years is very similar (i.e., meaningful). I would not recommend for instance rescaling time using the sd. 
Cécile

**Comment by fcudhea** [comment]
Thank you very much for the response.

I have a follow up question. If you were only concerned with avoiding numerical issues, would you consider rescaling using sd (or a value roughly close to the sd) to be a useful option? 

I ask because, for the project I am working on, I am using the probit model (our outcome of interest is an ordinal variable) where I find the interpretation of the parameter estimates to be already difficult enough that I am inclined to use prediction plots to interpret the resulting model anyway (and so would rather prioritize avoiding computational issues).

**Comment by CecileProust-Lima** [comment]
I never do that, I always prefer to find a good rescaling that I can easily communicate on (100 days, 1 months, 10 years, etc ...) but this is up to you! In the end, this is only a parameterization, the fit should not change. 
Cécile

**Comment by fcudhea** [comment]
Great. Thank you so much for your insight on this. I greatly appreciate it.
